//= util/[logger.js, core.js, config.js, module-manager.js]
//= util/[module.js, config.js, url.js, share-util.js]
//= model
//= player/contentless.js
//= player/micro-player/[model, manager, bento]
//= player/micro-player/[player-overrides.js, exports.js]
//= player/vmap/[model, manager]
//= player/vmap/[managers.js, exports.js]
//= player.js
//= util/[static-methods.js, jquery-plugin.js, end-slate-loader.js, finish.js]