//= util/[core.js, config.js]
//= util/[logger.js, module.js, config.js, url.js, share-util.js]
//= model
//= player/micro-player/[model, manager, bento]
//= player/micro-player/[player-overrides.js, exports.js]
//= player/vmap/[model, manager]
//= player/vmap/[managers.js, exports.js]
//= player.js
//= util/[jquery-plugin.js, end-slate-loader.js, finish.js]